# Image Node
FROM node:20

# Dossier de travail
WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer dépendances
RUN npm install

# Copier le reste
COPY . .

# Exposer le port
EXPOSE 3000

# Lancer le serveur
CMD ["npm", "run", "dev"]