stages:
  - build
  - test
  - deploy
 
variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
 
build_job:
  stage: build
  image: docker:24.0.2
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
 
test_job:
  stage: test
  image: node:20-alpine
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - coverage/
 
deploy_job:
  stage: deploy
  image: alpine:3.18
  script:
    - sh deploy.sh
